apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    volume.kubernetes.io/selected-node: ip-10-0-135-28.us-east-2.compute.internal
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: cf30ddb5-ffa8-4d1c-b7cb-7334d7ecf487
  name: giteadb
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pvc-8ba6cf5c-ffec-45b4-9a87-702026733d62
